Output .github/demos/since.gif
Require nyaa-cli

Set TypingSpeed 80ms

Set Shell "bash"
Set FontSize 24
Set BorderRadius 20
Set Width 1200
Set Height 1300
Set Margin 80
Set MarginFill "#111122"
Set Padding 30
Set Theme "Dark Pastel"
Set WindowBar Colorful
Set WindowBarSize 80

Type "clear" Enter

Type "Download all episodes of Witch Watch from episode 7 by Erai" Sleep 3s Ctrl+a Ctrl+k

Type "nyaa-cli --name 'witch watch' --from 7 --uploader 'erai'" Enter
Sleep 20s 