Output .github/demos/range.gif
Require nyaa-cli

Set TypingSpeed 80ms

Set Shell "bash"
Set FontSize 24
Set BorderRadius 20
Set Width 1200
Set Height 1450
Set Margin 80
Set MarginFill "#111122"
Set Padding 30
Set Theme "Dark Pastel"
Set WindowBar Colorful
Set WindowBarSize 80

Sleep 300ms

Type "Download episodes 16 through 20 of Solo Leveling" Sleep 2s Ctrl+a Ctrl+k

Type "nyaa-cli --name 'solo leveling' --from 16 --to 20" Enter
Sleep 20s 