Output .github/demos/basic.gif
Require nyaa-cli

Set TypingSpeed 80ms

Set Shell "bash"
Set FontSize 24
Set BorderRadius 20
Set Width 1200
Set Height 900
Set Margin 80
Set MarginFill "#111122"
Set Padding 30
Set Theme "Dark Pastel"
Set WindowBar Colorful
Set WindowBarSize 80

Sleep 300ms

Type "Download a single episode of Solo Leveling (episode 22)" Sleep 3s Ctrl+a Ctrl+k

Type "nyaa-cli --name 'solo leveling' --episode 22" Enter
Sleep 12s 